# Generated by Django 2.2 on 2021-06-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
