# Generated by Django 2.2 on 2021-06-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0002_auto_20210602_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='poker_players',
            field=models.ManyToManyField(related_name='poker_players', to='poker_app.User'),
        ),
    ]
