# Generated by Django 2.2 on 2021-06-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0002_auto_20210610_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(),
        ),
    ]
