# Generated by Django 2.2 on 2021-06-03 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0003_auto_20210602_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('game_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to='poker_app.Game')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='poker_app.User')),
            ],
        ),
    ]
