# Generated by Django 2.2 on 2021-06-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0003_game_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(),
        ),
    ]
