# Generated by Django 2.2 on 2021-06-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0004_auto_20210601_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
