# Generated by Django 2.2 on 2021-06-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker_app', '0005_auto_20210610_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(),
        ),
    ]
